[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
